"use client";

import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { MAHER_HERO_WATCHLIST } from "@/lib/maherHeroWatchlist";

type Pick={symbol:string;name:string;market:"US";price:number;changePct:number;volumeRatio:number;rsi:number;macdSignal:"bullish"|"bearish"|"neutral";trend:"up"|"down"|"sideways";breakout:"early"|"retest"|"late"|"none";resistanceDistancePct:number;stopDistancePct:number;score:number;classification:string;reasons:string[];warnings?:string[];available?:boolean;entryLow:number;entryHigh:number;stopLoss:number;target1:number;target2:number;target3:number;buyTiming:string;sellTiming:string;preferredSession:string;invalidation:string;riskReward:number;weeklyTrend?:string;dailyTrend?:string;hourlyTrend?:string;intradayTrend?:string};
type RadarPick=Pick&{detectedAt:string;updatedAt:string;previousScore?:number};
type Quote={symbol:string;price?:number;changePct?:number;rsi?:number;macdSignal?:"bullish"|"bearish"|"neutral";volumeRatio?:number;resistance?:number;support?:number;atr?:number;signal?:"hold"|"near_target"|"partial_sell"|"exit"|"danger"};
type Holding={id:string;symbol:string;buyPrice:number;quantity:number;buyDate:string;buyFee:number;customTarget?:number;manualPrice?:number;note?:string;longTerm:boolean;createdAt:string};
type Sale={id:string;symbol:string;quantity:number;buyPrice:number;sellPrice:number;fee:number;soldAt:string;realized:number};
type View=Holding&{quote?:Quote;price:number;marketValue:number;cost:number;pnl:number;pnlPct:number;target1:number;target2:number;protectiveStop:number;status:string;advice:string};

const HOLDINGS_KEY="maher-hero-holdings-v2",SALES_KEY="maher-hero-sales-v1",RADAR_KEY="maher-hero-radar-v2";
const DEFAULT_HOLDINGS:Holding[]=[["JLHL",17.08,26],["JSPR",0.6628,300],["TNDM",16.30,16],["AMWL",11.49,10],["FIG",24.09,4],["KLXE",2.60,100],["OPEN",4.67,25],["INTC",110.58,4]].map(([symbol,buyPrice,quantity])=>({id:`seed-${symbol}`,symbol:String(symbol),buyPrice:Number(buyPrice),quantity:Number(quantity),buyDate:"2026-07-13",buyFee:0,longTerm:false,createdAt:new Date().toISOString()}));
async function json(r:Response){if(!(r.headers.get("content-type")||"").includes("application/json"))throw new Error(`تعذر الوصول للخدمة (${r.status})`);return r.json()}
function money(v:number){if(!v)return "—";const d=Math.abs(v)<1?4:2;return `${v.toLocaleString("en-US",{minimumFractionDigits:d,maximumFractionDigits:d})} $`}
function stars(score:number){return "★★★★★☆☆☆☆☆".slice(Math.max(0,5-Math.round(score/20)),Math.max(0,10-Math.round(score/20)))}
function metrics(p:RadarPick,capital:number){const checks=[p.trend==="up",p.macdSignal==="bullish",p.rsi>=48&&p.rsi<=70,p.volumeRatio>=1.5,["early","retest"].includes(p.breakout),p.resistanceDistancePct>=2,p.stopDistancePct<=4];const met=checks.filter(Boolean).length;const liquidity=Math.min(100,Math.round(p.volumeRatio/3*100));const breakout=p.breakout==="early"?95:p.breakout==="retest"?88:p.breakout==="late"?25:35;const confidence=Math.round((p.score*.65)+(met/7*35));const heat=Math.max(1,Math.min(5,Math.round((liquidity+breakout+p.score)/60)));const moveDone=p.breakout==="late"?90:p.changePct>15?75:p.changePct>7?55:p.changePct>3?35:20;const style=p.score>=90?"مضاربة يومية":p.score>=80?"سكالب / يومي":p.score>=65?"مراقبة سوينغ":"انتظار";const qty=p.entryHigh?Math.floor((capital*.2)/p.entryHigh):0;const invested=qty*p.entryHigh;const profits=[p.target1,p.target2,p.target3].map(t=>qty?Math.max(0,(t-p.entryHigh)*qty):0);const missing=[!checks[0]&&"اتجاه صاعد",!checks[1]&&"MACD إيجابي",!checks[2]&&"RSI مناسب",!checks[3]&&"سيولة أقوى",!checks[4]&&"اختراق أو إعادة اختبار",!checks[5]&&"مسافة آمنة للمقاومة",!checks[6]&&"وقف أقرب"].filter(Boolean) as string[];return{met,confidence,liquidity,breakout,heat,moveDone,style,qty,invested,profits,missing}}
function ago(iso:string,now:number){const s=Math.max(0,Math.floor((now-new Date(iso).getTime())/1000));return s<60?`قبل ${s} ثانية`:s<3600?`قبل ${Math.floor(s/60)} دقيقة`:`قبل ${Math.floor(s/3600)} ساعة`}

export default function Home(){
 const [tab,setTab]=useState<"radar"|"portfolio"|"history">("radar"),[capital,setCapital]=useState(5000),[riskPct,setRiskPct]=useState(1),[loading,setLoading]=useState(false);
 const [radar,setRadar]=useState<RadarPick[]>([]),[scanned,setScanned]=useState(0),[progress,setProgress]=useState(0),[currentSymbol,setCurrentSymbol]=useState(""),[provider,setProvider]=useState("");
 const [marketOpen,setMarketOpen]=useState(false),[holdings,setHoldings]=useState<Holding[]>([]),[sales,setSales]=useState<Sale[]>([]),[quotes,setQuotes]=useState<Record<string,Quote>>({});
 const [portfolioLoading,setPortfolioLoading]=useState(false),[showAdd,setShowAdd]=useState(false),[error,setError]=useState(""),[portfolioUpdated,setPortfolioUpdated]=useState("لم يتم التحديث يدويًا");
 const [filter,setFilter]=useState("all"),[sort,setSort]=useState("priority"),[now,setNow]=useState(Date.now()),[form,setForm]=useState({symbol:"",buyPrice:"",quantity:"",buyDate:new Date().toISOString().slice(0,10),buyFee:"0",manualPrice:"",customTarget:"",note:""});
 const scanning=useRef(false);
 useEffect(()=>{try{const v2=localStorage.getItem(HOLDINGS_KEY),v1=localStorage.getItem("maher-hero-holdings-v1");setHoldings(v2?JSON.parse(v2):v1?JSON.parse(v1):DEFAULT_HOLDINGS);setSales(JSON.parse(localStorage.getItem(SALES_KEY)||"[]"));setRadar(JSON.parse(localStorage.getItem(RADAR_KEY)||"[]"))}catch{setHoldings(DEFAULT_HOLDINGS)}},[]);
 useEffect(()=>{if(holdings.length)localStorage.setItem(HOLDINGS_KEY,JSON.stringify(holdings))},[holdings]);useEffect(()=>{localStorage.setItem(SALES_KEY,JSON.stringify(sales))},[sales]);useEffect(()=>{if(radar.length)localStorage.setItem(RADAR_KEY,JSON.stringify(radar))},[radar]);useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
 const refreshClock=useCallback(async()=>{try{const d=await json(await fetch("/api/market/clock",{cache:"no-store"}));setMarketOpen(Boolean(d.isOpen))}catch{}},[]);useEffect(()=>{refreshClock();const t=setInterval(refreshClock,60000);return()=>clearInterval(t)},[refreshClock]);
 const refreshPortfolio=useCallback(async()=>{if(!holdings.length)return;setPortfolioLoading(true);setError("");try{const d=await json(await fetch("/api/portfolio/quotes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbols:holdings.map(h=>h.symbol)})}));const next:Record<string,Quote>={};for(const q of d.quotes||[])next[q.symbol]=q;setQuotes(next);setPortfolioUpdated(new Date().toLocaleTimeString("ar-SA"))}catch(e){setError(e instanceof Error?e.message:"تعذر تحديث المحفظة")}finally{setPortfolioLoading(false)}},[holdings]);
 const analyze=useCallback(async()=>{if(scanning.current)return;scanning.current=true;setLoading(true);setError("");setProgress(0);setScanned(0);try{let completed=0;const queue=[...MAHER_HERO_WATCHLIST];const worker=async()=>{while(queue.length){const symbol=queue.shift();if(!symbol)return;setCurrentSymbol(symbol);try{const d=await json(await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({market:"US",capital,riskPct,automatic:true,symbol})}));const p=d.picks?.[0] as Pick|undefined;if(p){const stamp=new Date().toISOString();setRadar(prev=>{const old=prev.find(x=>x.symbol===symbol);const next=prev.filter(x=>x.symbol!==symbol);next.push({...p,detectedAt:old?.detectedAt||stamp,updatedAt:stamp,previousScore:old?.score});return next});setProvider(d.provider||"alpaca-multi-timeframe")}}catch(e){setError(prev=>prev||(e instanceof Error?e.message:"تعذر التحليل"))}finally{completed++;setScanned(completed);setProgress(Math.round(completed/MAHER_HERO_WATCHLIST.length*100))}}};await Promise.all([worker(),worker(),worker()])}finally{setCurrentSymbol("");setLoading(false);scanning.current=false}},[capital,riskPct]);
 const opportunityCount=radar.filter(p=>p.available!==false&&p.score>=90).length,readyCount=radar.filter(p=>p.score>=80).length,watchCount=radar.filter(p=>p.score>=65&&p.score<80).length;
 const shown=useMemo(()=>radar.filter(p=>filter==="all"||filter==="owned"?filter!=="owned"||holdings.some(h=>h.symbol===p.symbol):filter==="90"?p.score>=90:filter==="80"?p.score>=80:filter==="liquidity"?p.volumeRatio>=2:filter==="breakout"?["early","retest"].includes(p.breakout):p.classification.includes(filter)).sort((a,b)=>sort==="score"?b.score-a.score:sort==="liquidity"?b.volumeRatio-a.volumeRatio:(metrics(b,capital).confidence-metrics(a,capital).confidence)||b.score-a.score),[radar,filter,sort,holdings,capital]);
 const views:View[]=useMemo(()=>holdings.map(h=>{const q=quotes[h.symbol],price=h.manualPrice||q?.price||h.buyPrice,cost=h.buyPrice*h.quantity+h.buyFee,marketValue=price*h.quantity,pnl=marketValue-cost,pnlPct=cost?pnl/cost*100:0,atr=q?.atr||price*.03,target1=h.customTarget||Math.max(cost/Math.max(1,h.quantity),q?.resistance||price*1.06),target2=Math.max(target1,price+atr*2),protectiveStop=pnl>0?Math.max(cost/Math.max(1,h.quantity),price-atr*1.2):(q?.support||price-atr*1.5),status=pnlPct<-20?"خسارة كبيرة":pnlPct<0?"تحت التكلفة":price>=target1*.98?"قريب من الهدف":"احتفاظ",advice=pnlPct<0?"لا تعزز عشوائيًا؛ راقب الدعم.":"احمِ الربح بوقف متحرك.";return{...h,quote:q,price,marketValue,cost,pnl,pnlPct,target1,target2,protectiveStop,status,advice}}),[holdings,quotes]);
 const totalCost=views.reduce((s,h)=>s+h.cost,0),portfolioValue=views.reduce((s,h)=>s+h.marketValue,0),totalPnl=views.reduce((s,h)=>s+h.pnl,0),realized=sales.reduce((s,x)=>s+x.realized,0);
 function saveHolding(e:FormEvent){e.preventDefault();const symbol=form.symbol.trim().toUpperCase(),buyPrice=Number(form.buyPrice),quantity=Number(form.quantity);if(!symbol||buyPrice<=0||quantity<=0)return setError("أدخل بيانات صحيحة");setHoldings(v=>[{id:crypto.randomUUID(),symbol,buyPrice,quantity,buyDate:form.buyDate,buyFee:Number(form.buyFee)||0,manualPrice:Number(form.manualPrice)||undefined,customTarget:Number(form.customTarget)||undefined,note:form.note,longTerm:false,createdAt:new Date().toISOString()},...v]);setShowAdd(false)}
 function sell(h:View){const qty=Number(prompt(`الكمية المباعة من ${h.symbol}`,String(h.quantity)));if(!qty||qty<=0||qty>h.quantity)return;const sellPrice=Number(prompt("سعر البيع",String(h.price)));if(!sellPrice)return;const fee=Number(prompt("عمولة البيع","2.11"))||0;const realizedValue=(sellPrice-h.buyPrice)*qty-fee-h.buyFee*(qty/h.quantity);setSales(v=>[{id:crypto.randomUUID(),symbol:h.symbol,quantity:qty,buyPrice:h.buyPrice,sellPrice,fee,soldAt:new Date().toISOString(),realized:realizedValue},...v]);setHoldings(v=>v.flatMap(x=>x.id!==h.id?[x]:qty===x.quantity?[]:[{...x,quantity:x.quantity-qty}]))}
 return <main>
  <nav className="topbar"><div className="brand">MAHER HERO <span>AI</span></div><div className={`live ${marketOpen?"is-live":""}`}><i/>{marketOpen?"السوق الأمريكي مفتوح":"السوق الأمريكي مغلق"}</div></nav>
  <header className="hero compact-hero"><div><div className="badge">Maher Hero Pro — v5.0</div><h1>غرفة عمليات الأسهم</h1><p>قرار واضح: هل أشتري؟ كيف أدخل؟ وكيف أخرج؟ مع ترتيب ذكي ومحاكاة ربح.</p></div><aside className="market-box"><span>آخر تحديث للمحفظة</span><strong>{portfolioUpdated}</strong><small>{portfolioLoading?"جارٍ التحديث...":"تحديث يدوي فقط"}</small></aside></header>
  <section className="tabbar"><button className={tab==="radar"?"active":""} onClick={()=>setTab("radar")}>خطة الـ22 سهمًا</button><button className={tab==="portfolio"?"active":""} onClick={()=>setTab("portfolio")}>محفظتي <b>{holdings.length}</b></button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}>الأرباح المحققة</button></section>{error&&<p className="error">{error}</p>}
  {tab==="radar"&&<section>
   <section className="panel controls us-controls"><label>رأس المال<input type="number" value={capital} onChange={e=>setCapital(Number(e.target.value))}/></label><label>المخاطرة %<input type="number" step=".1" value={riskPct} onChange={e=>setRiskPct(Number(e.target.value))}/></label><button onClick={analyze} disabled={loading}>{loading?`تحليل ${currentSymbol||"القائمة"}...`:"تحديث القائمة تدريجيًا"}</button><div className="source-note">المصدر: {provider||"Alpaca Multi-Timeframe"}</div></section>
   {loading&&<section className="panel scanner"><div className="scan-head"><strong>{scanned}/22</strong><span>{progress}%</span></div><div className="progress"><b style={{width:`${progress}%`,animation:"none"}}/></div></section>}
   <section className="summary pro-summary"><article><span>المحدّثة</span><strong>{radar.length}/22</strong></article><article><span>شراء مشروط 90+</span><strong>{opportunityCount}</strong></article><article><span>قريبة من الدخول</span><strong>{readyCount}</strong></article><article><span>مراقبة</span><strong>{watchCount}</strong></article></section>
   <section className="panel pro-filters"><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">كل الأسهم</option><option value="90">فوق 90</option><option value="80">فوق 80</option><option value="liquidity">سيولة قوية</option><option value="breakout">اختراق/إعادة اختبار</option><option value="owned">المملوكة فقط</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="priority">الأولوية الذكية</option><option value="score">أعلى تقييم</option><option value="liquidity">أعلى سيولة</option></select></section>
   <section className="cards pro-cards">{shown.map((p,i)=>{const m=metrics(p,capital),delta=(p.previousScore??p.score)-p.score;return <article className={`stock-card pro-card ${p.score>=90?"strong":p.score>=65?"watch":"avoid"}`} key={p.symbol}>
    <div className="pro-head"><div><span className="rank">#{i+1} من 22</span><h2>{p.symbol}</h2><p>{p.classification}</p><small>{ago(p.updatedAt,now)}</small></div><div className="score-stack"><strong>{p.score}</strong><span>/100</span><em>{stars(p.score)}</em>{p.previousScore!==undefined&&<small className={delta<0?"positive":delta>0?"negative":""}>{p.score-(p.previousScore||0)>=0?"▲":"▼"} {Math.abs(p.score-(p.previousScore||0))}</small>}</div></div>
    <div className="confidence"><span>الثقة {m.confidence}%</span><b><i style={{width:`${m.confidence}%`}}/></b></div>
    <div className="quick-metrics"><div><span>الشروط</span><strong>{m.met}/7</strong></div><div><span>الحرارة</span><strong>{"🔥".repeat(m.heat)}</strong></div><div><span>السيولة</span><strong>{m.liquidity}%</strong></div><div><span>الاختراق</span><strong>{m.breakout}%</strong></div><div><span>اكتمال الحركة</span><strong>{m.moveDone}%</strong></div><div><span>النوع</span><strong>{m.style}</strong></div></div>
    <div className="three-stage"><section><h3>1. هل أشتري؟</h3><p><b>{p.score>=90?"دخول مشروط":p.score>=80?"قريب من الدخول":"انتظار"}</b></p><small>الاتجاه: {p.trend} · MACD: {p.macdSignal} · RSI: {p.rsi.toFixed(1)} · RVOL: {p.volumeRatio.toFixed(2)}</small></section><section><h3>2. كيف أدخل؟</h3><p>{money(p.entryLow)} — {money(p.entryHigh)}</p><small>{p.buyTiming}<br/>{p.preferredSession}</small></section><section><h3>3. كيف أخرج؟</h3><p>{money(p.target1)} / {money(p.target2)} / {money(p.target3)}</p><small>الوقف: {money(p.stopLoss)}<br/>{p.sellTiming}</small></section></div>
    <div className="profit-sim"><b>محاكاة 20% من رأس المال</b><span>استثمار تقريبي: {money(m.invested)}</span><span>ربح هدف 1: +{money(m.profits[0])}</span><span>هدف 2: +{money(m.profits[1])}</span><span>هدف 3: +{money(m.profits[2])}</span></div>
    <details><summary>لماذا؟ وما الذي ينقصه؟</summary><div className="why-grid"><div><h4>نقاط القوة</h4>{(p.reasons||[]).map(x=><p key={x}>✓ {x}</p>)}</div><div><h4>ينقصه</h4>{m.missing.length?m.missing.map(x=><p key={x}>✗ {x}</p>):<p>✓ جميع الشروط الأساسية مكتملة</p>}</div><div><h4>سبب الاستبعاد/التحذير</h4>{(p.warnings||[]).map(x=><p key={x}>! {x}</p>)}<p>إلغاء الدخول: {p.invalidation}</p></div></div></details>
   </article>})}</section>
  </section>}
  {tab==="portfolio"&&<section><section className="portfolio-actions panel"><div><h2>الأسهم المملوكة</h2><p>لا يوجد تحديث تلقائي. اضغط التحديث يدويًا.</p></div><div className="action-buttons"><button onClick={()=>setShowAdd(v=>!v)}>+ إضافة سهم</button><button className="secondary-button" onClick={refreshPortfolio} disabled={portfolioLoading}>{portfolioLoading?"جارٍ التحديث":"تحديث الأسعار يدويًا"}</button></div></section>{showAdd&&<form className="panel holding-form" onSubmit={saveHolding}>{Object.entries({symbol:"الرمز",buyPrice:"متوسط التكلفة",quantity:"الكمية",manualPrice:"سعر يدوي",buyDate:"تاريخ الشراء",buyFee:"العمولة",customTarget:"هدف خاص",note:"ملاحظة"}).map(([k,l])=><label key={k}>{l}<input type={k==="buyDate"?"date":"text"} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<button>حفظ</button></form>}<section className="summary"><article><span>التكلفة</span><strong>{money(totalCost)}</strong></article><article><span>القيمة</span><strong>{money(portfolioValue)}</strong></article><article><span>المفتوح</span><strong className={totalPnl>=0?"positive":"negative"}>{money(totalPnl)}</strong></article><article><span>المحقق</span><strong>{money(realized)}</strong></article></section><div className="broker-table panel"><div className="broker-head"><span>السهم</span><span>الكمية</span><span>التكلفة</span><span>السعر</span><span>القيمة</span><span>النتيجة</span><span>%</span><span>الحالة</span><span>النصيحة</span><span>الأهداف</span><span>الوقف</span><span>الإجراء</span></div>{views.map(h=><div className="broker-row" key={h.id}><b>{h.symbol}</b><span>{h.quantity}</span><span>{money(h.buyPrice)}</span><span>{money(h.price)}</span><span>{money(h.marketValue)}</span><span>{money(h.pnl)}</span><span>{h.pnlPct.toFixed(2)}%</span><span>{h.status}</span><span>{h.advice}</span><span>{money(h.target1)} / {money(h.target2)}</span><span>{money(h.protectiveStop)}</span><button onClick={()=>sell(h)}>تم البيع</button></div>)}</div></section>}
  {tab==="history"&&<section className="panel"><h2>الأرباح المحققة: {money(realized)}</h2>{sales.map(s=><p key={s.id}><b>{s.symbol}</b> — {s.quantity} سهم — {money(s.realized)} — {new Date(s.soldAt).toLocaleString("ar-SA")}</p>)}</section>}
  <footer>البيانات تحليلية وليست ضمانًا للربح. تحقق من سعر التنفيذ قبل أي قرار.</footer>
 </main>
}